#!/usr/bin/env python
"""
This sample programs shows the rules jobs that have
commands, with a bit of detail about reads/writes.
"""

import argparse
from pyannolib import annolib

num_jobs = 0

def run(filename):

    build = annolib.AnnotatedBuild(filename)

    print "Build ID:", build.getBuildID()
    props = build.getProperties()
    print "CWD:", props["CWD"]
    print "AnnoDetail:", props["AnnoDetail"]


    def job_cb(job, junk):
        global num_jobs
        num_jobs += 1

        print job.getTextReport()



    build.parseJobs(job_cb)
    print "Total number of jobs:", num_jobs

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("annotation_file")

    options = parser.parse_args()

    run(options.annotation_file)

if __name__ == "__main__":
    main()
