#!/usr/bin/env python
"""
This sample shows the metrics of a build, and nothing else.
"""

import argparse
from pyannolib import annolib

num_jobs = 0

def run(filename):

    build = annolib.AnnotatedBuild(filename)

    def job_cb(job):
        # Do nothing
        pass

    # Skip all the jobs (parse them and throw them away)
    build.parseJobs(job_cb)

    # Now we have the metrics, which appear at the end of
    # the annotation file (that's why we had to parse all the jobs
    # first)
    metrics = build.getMetrics()

    keys = metrics.keys()
    keys.sort()
    for key in keys:
        value = metrics[key]
        print key, ":", value

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("annotation_file")

    options = parser.parse_args()

    run(options.annotation_file)

if __name__ == "__main__":
    main()
