#!/usr/bin/env python
"""
This sample shows the metrics of a build, and nothing else.
"""

import argparse
from pyannolib import annolib

def run(filename):

    build = annolib.AnnotatedBuild(filename)
    metrics = build.getMetrics()

    keys = metrics.keys()
    keys.sort()
    for key in keys:
        value = metrics[key]
        print key, ":", value

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("annotation_file")

    options = parser.parse_args()

    run(options.annotation_file)

if __name__ == "__main__":
    main()
