#!/usr/bin/env python
"""
This sample programs shows the rules jobs that have
commands, with a bit of detail about reads/writes.
"""

import argparse
from pyannolib import annolib

def run(filename):

    build = annolib.AnnotatedBuild(filename)

    print "Build ID:", build.getBuildID()
    props = build.getProperties()
    print "CWD:", props["CWD"]
    print "AnnoDetail:", props["AnnoDetail"]

    num_jobs = 0

    for job in build.iterJobs():
        num_jobs += 1
        print job.getTextReport()


    print "Total number of jobs:", num_jobs

def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("annotation_file")

    options = parser.parse_args()

    run(options.annotation_file)

if __name__ == "__main__":
    main()
