#!/usr/bin/env python
"""
Show the jobpath for any given target.
"""

import argparse
from pyannolib import annolib

# The jobs we are interested in.
jobs = {}

def show_jobpath(build, job):
    jobpath = build.getJobPath(job)

    for item in jobpath:
        print
        print item.getID()
        print
        print item.getTextReport()
        print "=" * 80

def run(filename, job_ids):

    # Gather all the jobs
    build = annolib.AnnotatedBuild(filename)

    for job in build.iterJobs():
        job_id = job.getID()
        if job_id in job_ids:
            jobs[job_id] = job

    # Report the job path for each job
    for job_id in job_ids:
        print "=" * 80
        job = jobs[job_id]
        show_jobpath(build, job)


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument("annotation_file")
    parser.add_argument("targets", nargs="+")

    options = parser.parse_args()

    run(options.annotation_file, options.targets)

if __name__ == "__main__":
    main()
