#!/usr/bin/env python
# Copyright (c) 2013-2014 by Cisco Systems, Inc.

import os
import unittest

from utlib import jenkins

# From each module, import the TestCase sub-class
from utlib.build import BuildTests
from utlib.jobpath import JobPathTests
from utlib.concat import ConcatTests
from utlib.jobseq import SeqTests
from utlib.dag import DAGTests


if __name__ == "__main__":
    # If we are running under Hudson/Jenkins, then output in JunitXML format
    if os.environ.has_key("HUDSON_URL"):
        jenkins.main(__name__, "unittest.xml")
    else:
        unittest.main(verbosity=2)
